# Generated by Django 3.1.8 on 2021-06-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superhero_name', models.CharField(max_length=50)),
                ('alter_ego_name', models.CharField(max_length=50)),
                ('primary_hero_ability', models.CharField(max_length=50)),
                ('secondary_hero_ability', models.CharField(max_length=50)),
                ('superhero_catchphrase', models.CharField(max_length=50)),
            ],
        ),
    ]
